load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "graph",
    srcs = ["kruskal.go"],
    importpath = "github.com/thenakulchawla/shenanigans/go-dsa/graph",
    visibility = ["//visibility:public"],
)

go_test(
    name = "graph_test",
    srcs = ["kruskal_test.go"],
    embed = [":graph"],
    deps = ["@com_github_stretchr_testify//require"],
)
