load("@gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/thenakulchawla/shenanigans

# Run `bazel run //:gazelle` to (re)generate BUILD.bazel files for parse-git and go-dsa.
gazelle(
    name = "gazelle",
    args = [
        "parse-git",
        "go-dsa",
    ],
)

exports_files(["go.mod", "go.work", "go.work.sum"])
