load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go-dsa_lib",
    srcs = ["main.go"],
    importpath = "github.com/thenakulchawla/shenanigans/go-dsa",
    visibility = ["//visibility:private"],
    deps = ["//go-dsa/backtracking"],
)

go_binary(
    name = "go-dsa",
    embed = [":go-dsa_lib"],
    visibility = ["//visibility:public"],
)
