load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "commitparser",
    srcs = ["parser.go"],
    importpath = "github.com/thenakulchawla/commitparser/commitparser",
    visibility = ["//visibility:public"],
)

go_test(
    name = "commitparser_test",
    size = "small",
    srcs = ["parser_test.go"],
    embed = [":commitparser"],
    deps = ["@com_github_stretchr_testify//require"],
)
