load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "queue",
    srcs = ["queue.go"],
    importpath = "github.com/thenakulchawla/shenanigans/go-dsa/queue",
    visibility = ["//visibility:public"],
)

go_test(
    name = "queue_test",
    srcs = ["queue_test.go"],
    embed = [":queue"],
    deps = ["@com_github_stretchr_testify//require"],
)
